DROP DATABASE IF EXISTS DOST_db;

CREATE DATABASE DOST_db;

CREATE USER 'syxzms6evb8xpuyu'@'3306'
GRANT ALL PRIVILEGES ON DOST_db.* TO 'syxzms6evb8xpuyu'@'3306';

USE DOST_db;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  profile_photo VARCHAR(255),
);

CREATE TABLE posts (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  user_id INTEGER NOT NULL,
  place_id INTEGER,
  caption VARCHAR(255) NOT NULL, -- DENORMALIZATION
  description TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT NOW(),
  archived BOOLEAN NOT NULL DEFAULT false,
  FOREIGN KEY (user_id) REFERENCES users(id),
);


CREATE TABLE comments (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  user_id INTEGER NOT NULL,
  post_id INTEGER NOT NULL,
  message VARCHAR(1000) NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT NOW(),
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);

CREATE TABLE post_likes (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  user_id INTEGER NOT NULL,
  post_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT NOW(),
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);
